/*
 * Generated by Ralink upnp XML converter:Mon Oct 27 20:17:52 CST 2014
 * Do not edit
 */
#include "xml_data.h"
#include "include/upnp_description.h"

extern char _binary_upnpxmldata_bin_start[];
char *upnpxmldata_location = &_binary_upnpxmldata_bin_start[0];

upnpxmldata_entry upnpxmldata_table[]= {
{XML_INDEX_InternetGatewayDevice, 
900
},
{XML_INDEX_x_lanhostconfigmanagement, 
602
},
{XML_INDEX_x_layer3forwarding, 
310
},
{XML_INDEX_x_wancommoninterfaceconfig, 
725
},
{XML_INDEX_x_wanipconnection, 
902
},
{XML_INDEX_x_wfadevicedesc, 
342
},
{XML_INDEX_x_wfawlanconfigscpd, 
577
},
{0 , 0},
};
